--- #YAML:1.0
name:                WWW-Comic-Plugin-f8d
version:             0.02
abstract:            WWW::Comic plugin to fetch f8d comic
license:             perl
author:              
    - David Precious <davidp@preshweb.co.uk>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
    WWW::Comic::Plugin:            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
